### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by reaganking** [muneebalam/scrapenhl2#36]
When trying to run autoupdate or game charts:

>>> import scrapenhl2
>>> from scrapenhl2.scrape import autoupdate
autoupdate.autoupdate()
HTTPSConnectionPool(host='statsapi.web.nhl.com', port=443): Read timed out. (read timeout=5)
Failed on try 0 on url https://statsapi.web.nhl.com/api/v1/schedule?startDate=2009-09-01&endDate=2010-06-25
HTTPSConnectionPool(host='statsapi.web.nhl.com', port=443): Read timed out. (read timeout=5)
Failed on try 1 on url https://statsapi.web.nhl.com/api/v1/schedule?startDate=2009-09-01&endDate=2010-06-25
HTTPSConnectionPool(host='statsapi.web.nhl.com', port=443): Read timed out. (read timeout=5)
Failed on try 2 on url https://statsapi.web.nhl.com/api/v1/schedule?startDate=2009-09-01&endDate=2010-06-25
HTTPSConnectionPool(host='statsapi.web.nhl.com', port=443): Read timed out. (read timeout=5)
Failed on try 3 on url https://statsapi.web.nhl.com/api/v1/schedule?startDate=2009-09-01&endDate=2010-06-25
HTTPSConnectionPool(host='statsapi.web.nhl.com', port=443): Read timed out. (read timeout=5)
Failed on try 4 on url https://statsapi.web.nhl.com/api/v1/schedule?startDate=2009-09-01&endDate=2010-06-25
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapenhl2/scrape/autoupdate.py", line 10, in <module>
    import scrapenhl2.scrape.manipulate_schedules as manipulate_schedules
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapenhl2/scrape/manipulate_schedules.py", line 6, in <module>
    import scrapenhl2.scrape.schedules as schedules
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapenhl2/scrape/schedules.py", line 456, in <module>
    schedule_setup()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapenhl2/scrape/schedules.py", line 303, in schedule_setup
    generate_season_schedule_file(season)  # season schedule
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapenhl2/scrape/schedules.py", line 348, in generate_season_schedule_file
    write_season_schedule(df, season, force_overwrite)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapenhl2/scrape/schedules.py", line 152, in write_season_schedule
    schedule_setup()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapenhl2/scrape/schedules.py", line 303, in schedule_setup
    generate_season_schedule_file(season)  # season schedule
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scrapenhl2/scrape/schedules.py", line 342, in generate_season_schedule_file
    page2 = json.loads(page)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
>>> autoupdate.autoupdate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'autoupdate' is not defined

**Comment by reaganking** [comment]
Closing this as well. Issue appears to be with pytables. It doesn't appear to be supported or have plans to support python3.7.
